service: serverless-plugin-typetalk-example

plugins:
  - serverless-plugin-typetalk

custom:
  typetalk:
    token: ${env:TYPETALK_TOKEN}
    topicId: ${env:TYPETALK_TOPIC_ID}

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
